remove_words = {'metropolitan', 'area', 'metroplex', 'greater', 'region', 'county', 'metro', 'city', 'bay', 'y',
                'alrededores'}

us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "Nueva York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District Of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}

unmapped_city = {
    'brooklyn': 'new york-newark',
    'orange county': 'los angeles-long beach',
    'irvine': 'los angeles-long beach',
    'scottsdale': 'phoenix-mesa',
    'bronx': 'new york-newark',
    'west palm beach': 'miami-port st. lucie-fort lauderdale',
    'plano': 'dallas-fort worth',
    'queens county': 'new york-newark',
    'cambridge': 'boston-worcester-providence',
    'mountain view': 'san jose-san francisco-oakland',
    'boulder': 'denver-aurora',
    'littleton': 'denver-aurora',
    'marietta': 'atlanta--athens-clarke county--sandy springs',
    'alpharetta': 'atlanta--athens-clarke county--sandy springs',
    'tempe': 'phoenix-mesa',
    'bellevue': 'seattle-tacoma',
    'boca raton': 'miami-port st. lucie-fort lauderdale',
    'hollywood': 'miami-port st. lucie-fort lauderdale',
    'arlington': 'dallas-fort worth',
    'irving': 'dallas-fort worth',
    'katy': 'houston-the woodlands',
    'chandler': 'phoenix-mesa',
    'fremont': 'san jose-san francisco-oakland',
    'jersey city': 'new york-newark',
    'santa clara': 'san jose-san francisco-oakland',
    'sunnyvale': 'san jose-san francisco-oakland',
    'berkeley': 'san jose-san francisco-oakland',
    'pompano beach': 'miami-port st. lucie-fort lauderdale',
    'frisco': 'dallas-fort worth',
    'riverside': 'los angeles-long beach',
    'silver spring': 'washington-baltimore-arlington',
    'redmond': 'seattle-tacoma',
    'wilmington': 'philadelphia-reading-camden',
    'new alexandria': 'washington-baltimore-arlington',
    'beverly hills': 'los angeles-long beach',
    'santa monica': 'los angeles-long beach',
    'staten island': 'new york-newark',
    'gilbert': 'phoenix-mesa',
    'anaheim': 'los angeles-long beach',
    'mckinney': 'dallas-fort worth',
    'palo alto': 'san jose-san francisco-oakland',

}
